export const quotes = [
  { text: 'Hayat, siz başka planlar yaparken başınıza gelenlerdir.', author: 'John Lennon' },
  { text: 'Düşünüyorum, öyleyse varım.', author: 'René Descartes' },
  { text: 'Kendini bil.', author: 'Sokrates' },
  { text: 'Hayal gücü bilgiden daha önemlidir.', author: 'Albert Einstein' },
  { text: 'Eğitim, dünyanın seyrini değiştirmek için kullanabileceğiniz en güçlü silahtır.', author: 'Nelson Mandela' },
  { text: 'Ne kadar az bilirseniz, o kadar şiddetle savunursunuz.', author: 'Bertrand Russell' },
  { text: 'Zeka, değişime uyum sağlama yeteneğidir.', author: 'Stephen Hawking' },
  { text: 'Bir insanın zekası, verdiği cevaplardan değil, sorduğu sorulardan anlaşılır.', author: 'Albert Einstein' },
  { text: 'Dünyada görmek istediğin değişimin kendisi ol.', author: 'Mahatma Gandhi' },
  { text: 'İlim ilim bilmektir, ilim kendin bilmektir.', author: 'Yunus Emre' },
  { text: 'Karanlığa küfredeceğine bir mum yak.', author: 'Konfüçyüs' },
  { text: 'Başarı, başarısızlıktan başarısızlığa hevesini kaybetmeden gitmektir.', author: 'Winston Churchill' },
  { text: 'Rüzgarın yönünü değiştiremezsin ama yelkenlerini ayarlayabilirsin.', author: 'Jimmy Dean' },
  { text: 'Önyargıları kırmak, atom çekirdeğini parçalamaktan daha zordur.', author: 'Albert Einstein' },
  { text: 'Mantık sizi A noktasından B noktasına götürür. Hayal gücü ise her yere.', author: 'Albert Einstein' },
  { text: 'İnsanın kendiyle yüzleşmesi, en büyük cesarettir.', author: 'Carl Jung' },
  { text: 'Cesaret, korkunun yokluğu değil, korkuya karşı direnmektir.', author: 'Mark Twain' },
  { text: 'Hayat, bisiklet sürmek gibidir. Dengede kalmak için hareket etmeye devam etmelisiniz.', author: 'Albert Einstein' },
  { text: 'Hata yapmayan bir insan, yeni bir şey denememiş demektir.', author: 'Albert Einstein' },
  { text: 'Hayatta en hakiki mürşit ilimdir.', author: 'Mustafa Kemal Atatürk' },
  { text: 'Kendi yolunda yanlış gitmek, başkasının yolunda doğru gitmekten iyidir.', author: 'Dostoyevski' },
  { text: 'Zaman en iyi yazardır, her zaman mükemmel sonu yazar.', author: 'Charlie Chaplin' },
  { text: 'Sabır, acı bir bitkidir ama meyvesi tatlıdır.', author: 'Anonim' },
  { text: 'Hayatta hiçbir şeyden korkmayın, sadece anlamaya çalışın.', author: 'Marie Curie' },
  { text: 'Yapabileceğinize inanıyorsanız, haklısınız. Yapamayacağınıza inanıyorsanız, yine haklısınız.', author: 'Henry Ford' },
  { text: 'Asla, asla, asla pes etmeyin.', author: 'Winston Churchill' },
  { text: 'Kelimeler, en güçlü silahlardır.', author: 'Jean-Paul Sartre' },
  { text: 'Kendi aklını kullanma cesaretini göster!', author: 'Immanuel Kant' },
  { text: 'Mutluluk, varılacak bir istasyon değil, bir yolculuk şeklidir.', author: 'Margaret Lee Runbeck' },
  { text: 'Zaman, sahip olduğumuz en değerli hazinedir.', author: 'Theophrastus' },
  { text: 'Sadelik, en yüksek gelişmişlik düzeyidir.', author: 'Leonardo da Vinci' },
  { text: 'Hayat, geriye doğru anlaşılır, ancak ileriye doğru yaşanmalıdır.', author: 'Søren Kierkegaard' },
  { text: 'Her şey değişir, hiçbir şey aynı kalmaz.', author: 'Herakleitos' },
  { text: 'İnsanı en çok yoran şey, sakladığı sırlardır.', author: 'Sigmund Freud' },
  { text: 'Hayal kurmak, geleceği yaratmanın ilk adımıdır.', author: 'Victor Hugo' },
  { text: 'Konuşmadan önce düşün, düşündükten sonra konuş.', author: 'William Shakespeare' },
  { text: 'Bir insanı tanımak istiyorsan, ona güç ver.', author: 'Abraham Lincoln' },
  { text: 'Doğru olanı yapmak için her zaman doğru zamandır.', author: 'Martin Luther King Jr.' },
  { text: 'Bizi yok etmeyen şey, bizi daha güçlü kılar.', author: 'Friedrich Nietzsche' },
  { text: 'Hayat bir hikaye gibidir; ne kadar uzun olduğu değil, ne kadar iyi olduğu önemlidir.', author: 'Seneca' },
  { text: 'Neyi arıyorsan, sen osun.', author: 'Mevlânâ Celâleddîn-i Rûmî' },
  { text: 'Düşünmeden öğrenmek emek kaybıdır, öğrenmeden düşünmek tehlikelidir.', author: 'Konfüçyüs' },
  { text: 'Gerçek bilgi, cehaletinin sınırlarını bilmektir.', author: 'Konfüçyüs' },
  { text: 'Sınırlar sadece zihnimizdedir.', author: 'Anonim' },
  { text: 'Umut, uyanık insanların rüyasıdır.', author: 'Aristoteles' },
  { text: 'Sabır, bilgeliğin yoldaşıdır.', author: 'Augustinus' },
  { text: 'İmkansız sadece bir kelimedir.', author: 'Muhammed Ali' },
  { text: 'Söz ağızdan çıkana kadar senin esirindir, çıktıktan sonra sen onun esiri olursun.', author: 'Hz. Ali' },
  { text: 'Yaşam, kendini bulmakla ilgili değildir; kendini yaratmakla ilgilidir.', author: 'George Bernard Shaw' },
  { text: 'Huzur, içeriden gelir; onu dışarıda arama.', author: 'Buddha' },
  { text: 'Kendi hayatınızın yazarı olun.', author: 'Anonim' },
  { text: 'Başarısızlık, daha zekice başlama fırsatından başka bir şey değildir.', author: 'Henry Ford' },
  { text: 'Ne istersen ol, ama en iyisi ol.', author: 'Abraham Lincoln' },
  { text: 'Dostluk, iki bedende yaşayan tek bir ruhtur.', author: 'Aristoteles' },
  { text: 'Hayallerinizin yönünde güvenle gidin; hayal ettiğiniz hayatı yaşayın.', author: 'Henry David Thoreau' },
  { text: 'Hayat, fırtınanın geçmesini beklemek değil, yağmurda dans etmeyi öğrenmektir.', author: 'Vivian Greene' },
  { text: 'En büyük risk, hiçbir risk almamaktır.', author: 'Mark Zuckerberg' },
  { text: 'Mutlu olmak istiyorsan, bir amaca bağlan; insanlara veya eşyalara değil.', author: 'Albert Einstein' },
  { text: 'Sevginin olduğu yerde hayat vardır.', author: 'Mahatma Gandhi' },
  { text: 'Başlamak için mükemmel olmak zorunda değilsin, ama mükemmel olmak için başlamak zorundasın.', author: 'Zig Ziglar' },
  { text: 'Zorluklar, sıradan insanları sıra dışı bir kadere hazırlar.', author: 'C.S. Lewis' },
  { text: 'Zamanı geri alamazsın, ama geleceği yeniden yazabilirsin.', author: 'Anonim' },
  { text: 'Her gün yeni bir başlangıçtır.', author: 'George Eliot' },
  { text: 'Kendiniz olun, çünkü diğer herkes zaten kapıldı.', author: 'Oscar Wilde' },
  { text: 'Hedefsiz bir gemiye hiçbir rüzgar yardım edemez.', author: 'Seneca' },
  { text: 'Hayat, cesurları sever.', author: 'Anonim' },
  { text: 'Her fırtına bir gün diner.', author: 'Anonim' },
  { text: 'En uzun yolculuklar, tek bir adımla başlar.', author: 'Laozi' },
  { text: 'Barış, bir gülümsemeyle başlar.', author: 'Rahibe Teresa' },
];
